<?php

return [
    'page_title' => 'Custody receipt — :number',
    'title' => 'Custody receipt',
    'receipt_number' => 'Receipt number',
    'assignment_date' => 'Assignment date',
    'device_name' => 'Device name',
    'device_type' => 'Device type',
    'serial_number' => 'Serial number',
    'recipient' => 'Recipient employee',
    'department' => 'Department',
    'assigned_by' => 'Storekeeper / assigned by',
    'acknowledgment' => 'I, the undersigned, acknowledge receipt of the above custody item in its current condition and undertake to preserve it and return it when no longer needed or upon request, in accordance with applicable ministry regulations.',
    'signature_storekeeper' => 'Storekeeper',
    'signature_recipient' => 'Recipient employee',
    'signature_supervisor' => 'Inventory supervisor',
    'footer' => 'Document automatically generated by :app_name — MTNIMA © :year',
];
